spring.application.name=plantcare

# Supabase Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Supabase Storage
spring.supabase.url=${SUPABASE_URL}
spring.supabase.bucket=${SUPABASE_BUCKET}
spring.supabase.key=${SUPABASE_KEY}

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Authenticate
spring.signer-key=${SIGNER_KEY}