package com.qtrong.plantcare.enums;

public enum PlantDisease {
    APPLE_SCAB,
    APPLE_BLACK_ROT,
    APPLE_CEDAR_APPLE_RUST,
    APPLE_HEALTHY,

    BLUEBERRY_HEALTHY,

    CHERRY_POWDERY_MILDEW,
    CHERRY_HEALTHY,

    CORN_CERCOSPORA_LEAF_SPOT_GRAY_LEAF_SPOT,
    CORN_COMMON_RUST,
    CORN_NORTHERN_LEAF_BLIGHT,
    CORN_HEALTHY,

    GRAPE_BLACK_ROT,
    GRAPE_ESCA_BLACK_MEASLES,
    GRAPE_LEAF_BLIGHT_ISARIOPSIS_LEAF_SPOT,
    GRAPE_HEALTHY,

    ORANGE_HUANGLONGBING_CITRUS_GREENING,

    PEACH_BACTERIAL_SPOT,
    PEACH_HEALTHY,

    BELL_PEPPER_BACTERIAL_SPOT,
    BELL_PEPPER_HEALTHY,

    POTATO_EARLY_BLIGHT,
    POTATO_LATE_BLIGHT,
    POTATO_HEALTHY,

    RASPBERRY_HEALTHY,

    SOYBEAN_HEALTHY,

    SQUASH_POWDERY_MILDEW,

    STRAWBERRY_LEAF_SCORCH,
    STRAWBERRY_HEALTHY,

    TOMATO_BACTERIAL_SPOT,
    TOMATO_EARLY_BLIGHT,
    TOMATO_LATE_BLIGHT,
    TOMATO_LEAF_MOLD,
    TOMATO_SEPTORIA_LEAF_SPOT,
    TOMATO_SPIDER_MITES_TWO_SPOTTED_SPIDER_MITE,
    TOMATO_TARGET_SPOT,
    TOMATO_YELLOW_LEAF_CURL_VIRUS,
    TOMATO_MOSAIC_VIRUS,
    TOMATO_HEALTHY
}
